
<div class="table-responsive">
    <table class="table">
        <tr>

            <td class="active"><h3>Прізвище</h3></td>
            <td class="active"><h3>Ім'я</h3></td>
            <td class="active"><h3>По-батькові</h3></td>
            <td class="active"><h3>Контакти</h3></td>
      

        </tr>


<?php if (!$seekerses==null){?>
    <?php foreach ($seekerses as $seekers): ?>

        <tr>
            
            <td class="active"><?=$seekers['surname']?></td>
            <td class="active"><?=$seekers['jobseekername']?></td>
            <td class="active"><?=$seekers['father']?></td>
            <td class="active"><?=$seekers['contact']?></td>

            <td><a href="/showjobsearch/<?= $seekers['id'] ?>" class="btn btn-info" role="button"><i class="fa fa-search" aria-hidden="true"></i> Переглянути</a><br></td>
        <tr>
    <?php endforeach; }?>

        
    </table>
    