<h2 class="fontColorHeader">Вас вітає програма працевлаштування осіб з інвалідністю та інших верств населення
    <?=$user['region']?></h2>

<h3>Керівник та відповідальна особа: <b><?=$user['surname']?>  <?=$user['username']?> <?=$user['father']?></b><br>
    Початок роботи Програми: <b>2016 рік</b>
</h3>




<!--Регіон Вашої роботи - --><?//=$user['region']?><!--<br><br><br>-->


<?php // echo '<img src="data:image/jpeg;base64,'.base64_encode($user['foto']).'" />'; ?>
<img src="img/01.png" />


<br><br>
<a href="/thirdpage" class="btn btn-primary" role="button">Перейти до бази даних</a>


<!--<br><br><br>-->
<!---->
<!---->
<!---->
<!--<br><br><br><br><br>-->

<!--<button>Go ajax ha-ha-ha</button>-->
<!--<div id="ajax_test">-->
<!---->
<!--</div>-->
<!---->
<!---->
<!--<script>-->
<!--    $('button').click(function () {-->
<!---->
<!--        $.get('/ajax_test', function (data) {-->
<!---->
<!--            var fruits = JSON.parse(data);-->
<!--            $('#ajax_test').append(fruits['aranges']);-->
<!--            $('#ajax_test').append('<br>');-->
<!--            $('#ajax_test').append(fruits['apples']);-->
<!--        });-->
<!---->
<!---->
<!--    });-->
<!---->
<!---->
<!---->
<!--</script>-->

