<h4>
    <form method="post">
        <fieldset>


            <legend>Редагувати анкету шукача роботи:</legend>



            <div class="row"><div class="col-md-6 slabel">
                    <label> Прізвище:</div><div class="col-md-6 svalue">
                    <input type="text"  name="surname" value="<?=$oldjobseeker['surname']?>">
                    </label><br><br></div></div>



            <div class="row"><div class="col-md-6 slabel">
                    <label>Ім'я:</div><div class="col-md-6 svalue">
                    <input type="text" name="jobseekername" value="<?=$oldjobseeker['jobseekername']?>">
                    </label><br><br></div></div>



            <div class="row"><div class="col-md-6 slabel">
                    <label>По-батькові:</div><div class="col-md-6 svalue">
                    <input type="text" name="father" value="<?=$oldjobseeker['father']?>">
                    </label><br><br></div></div>



            <div class="row"><div class="col-md-6 slabel">
                    <label> Дата народження:</div><div class="col-md-6 svalue">
                    <input type="date" name="birthdate" value="<?=$oldjobseeker['birthdate']?>">
                    </label><br><br></div></div>



            <div class="row"><div class="col-md-6 slabel">
                    <label> Стать:</div><div class="col-md-6 svalue">
                    <select name="stat">
                        <option value="<?=$oldjobseeker['stat']?>">
                            <?php if ($oldjobseeker['stat']=='male'){echo 'чоловіча';}
                            elseif ($oldjobseeker['stat']=='female'){echo 'жіноча';}
                            else{echo 'Стать не задана';}?>
                        </option>
                        <option value="male">
                            Чоловік
                        </option>
                        <option value="female">
                            Жінка
                        </option>
                    </select>
                    </label><br><br></div></div>

            <div class="row"><div class="col-md-6 slabel">
                    <label> Паспорт:</div><div class="col-md-6 svalue">
                    <input type="text" name="pasport" value="<?=$oldjobseeker['pasport']?>">
                    </label><br><br></div></div>



            <div class="row"><div class="col-md-6 slabel">
                    <label> Адреса:</div><div class="col-md-6 svalue">
                    <input type="text" name="adress" value="<?=$oldjobseeker['adress']?>"><br>
                    </label><br></div></div>



            <div class="row"><div class="col-md-6 slabel">
                    <label> Номер телефону:</div><div class="col-md-6 svalue">
                    <input type="text" name="contact" value="<?=$oldjobseeker['contact']?>"><br>
                    </label><br></div></div>



            <div class="row"><div class="col-md-6 slabel">
                    <label> E-mail:</div><div class="col-md-6 svalue">
                    <input type="email" name="email" value="<?=$oldjobseeker['email']?>"><br>
                    </label><br></div></div>



            <div class="row"><div class="col-md-6 slabel">
                    <label> Група інвалідності:</div><div class="col-md-6 svalue">
                    <select name="grup">
                        <option value="<?=$oldjobseeker['grup']?>">
                            <?=($oldjobseeker['grup'])?>
                        </option>
                        <option value="Без інвалідності">
                            Без інвалідності
                        </option>
                        <option value="І А - група">
                            І А - група
                        </option>
                        <option value="І Б - група">
                            І Б - група
                        </option>
                        <option value="ІІ - група">
                            ІІ - група
                        </option>
                        <option value="ІІІ - група">
                            ІІІ - група
                        </option>
                    </select>
                    </label><br><br></div></div>



            <div class="row"><div class="col-md-6 slabel">
                    <label> Дата звільнення з останнього місця роботи:</div><div class="col-md-6 svalue">
                    <input type="date" name="freedate" value="<?=$oldjobseeker['freedate']?>">
                    </label><br><br></div></div>
            



        </fieldset>
        <button class="btn btn-success btn-lg" type="submit"><i class="fa fa-plus-circle" aria-hidden="true"></i> Додати анкету</button>
        <a href="/thirdpage" class="btn btn-danger btn-lg" role="button"><i class="fa fa-ban" aria-hidden="true"></i> Відмінити</a>
    </form>
</h4>
<b id="flash"><?=\Library\Session::getFlash()?></b>