
<h2>Анкета</h2>
<a href="/userupdate/<?= $user['id'] ?>" class="btn btn-primary" role="button">Змінити дані працівника</a><br><br>

Прізвище:<?= $user['surname'] ?><br>
Ім'я:<?= $user['username'] ?><br>
По-батькові:<?= $user['father'] ?><br>
Регіон:<?= $user['id_region'] ?><br>
Працює з:<?= $user['startwork'] ?><br>
Контакти:<?= $user['contact'] ?><br>

Статус:<?php if ($user['status']==1){echo 'адміністратор';}
elseif ($user['status']==2){echo 'керівник регіону';}
else{echo 'користувач';}?><br>
E-mail:<?= $user['email'] ?><br>
<?php  echo '<img src="data:image/jpeg;base64,'.base64_encode($user['foto']).'" />'; ?><br>
<br><hr><br>