
<div class="text-right"><a href="/updatecompany/<?= $company['id'] ?>" class="btn btn-success" role="button">Редагувати</a>
    <a href="" class="btn btn-danger" role="button">Видалити</a><br><br>
        <h3>
            <div class="row svalueanketa">
                Назва організації(установи): <span class="slabelanketa"><?=$company['company']?></span><br>
                ПІБ керівника: <span class="slabelanketa"><?= $company['PIB'] ?></span><br>
                Номер телефону: <span class="slabelanketa"><?= $company['telefon'] ?></span><br>
                Контакти: <span class="slabelanketa"><?= $company['contact'] ?></span><br>
                E-mail: <span class="slabelanketa"><?= $company['email'] ?></span><br>
                <br>

            </div>
        </h3>