<br><br><br>
<div class="row">
    <div class="col-xs-6 col-md-6">
        <a href="/jobseekercreate" class="thumbnail">
            <p>
                <i class="fa fa-user-plus fa-5x" aria-hidden="true"></i>
            </p>
            <p>
                <h3>Додати анкету нового шукача роботи</h3>
            </p>
        </a>
    </div>

    <div class="col-xs-6 col-md-6">
        <a href="/alljobseekeres" class="thumbnail">
            <p>
                <i class="fa fa-user fa-5x" aria-hidden="true"></i>
            </p>
            <p>
            <h3>Переглянути анкети шукачів роботи</h3>
            </p>
        </a>
    </div>
</div>


<br><br>
<hr class="coloris">
<br><br><br>


<div class="row">
    <div class="col-xs-6 col-md-3">
        <a href="/showallcompany/1" class="thumbnail">
            <p>
                <i class="fa fa-university fa-5x fa-shadow" aria-hidden="true"></i>
            </p>
            <p>
            <h3>місцеві органи державної влади</h3>
            </p>
        </a>
    </div>
    <div class="col-xs-6 col-md-3">
        <a href="/showallcompany/2" class="thumbnail">
            <p>
                <i class="fa fa-archive fa-5x fa-shadow" aria-hidden="true"></i>
            </p>
            <p>
                <h3>центри <p>зайнятості</p></h3>
            </p>
        </a>
    </div>
    <div class="col-xs-6 col-md-3">
        <a href="/showallcompany/3" class="thumbnail">
            <p>
                <i class="fa fa-users fa-5x fa-shadow" aria-hidden="true"></i>
            </p>
            <p>
            <h3>громадські об'єднання</h3>
            </p>
        </a>
    </div>
    <div class="col-xs-6 col-md-3">
        <a href="/showallcompany/4" class="thumbnail">
            <p>
                <i class="fa fa-industry fa-5x fa-shadow" aria-hidden="true"></i>
            </p>
            <p>
            <h3>приватний <p>бізнес</p></h3>
            </p>
        </a>
    </div>
</div>
