<?php var_dump($grupuinval);?>


<div class="row">
<h1 class="stitzvit">Узагальнений звіт про результати роботи центру
    працевлаштування громадян Київського обласного осередку ГОІ "ВАПІ" за ІІ квартал 2016 року<br><br></h1>

    <div class="stilozvit">
        1. Кількість осіб, що звернулись до центру: <?=$zvernen?> осіб:
        <div class="stiloznachzvit">- з них жінок: <?=$zvernenwoman?>;</div>
        <div class="stiloznachzvit">- з них чоловіків: <?=$zvernenman?>;</div>
    </div>
    <div class="stilozvit">
        2. З них мають інвалідність: *знач* осіб:
        <?php foreach ($grupuinval as $grupinval): ?>
        <div class="stiloznachzvit">- з них <?=$grupinval['grup']?>: <?=$grupinval['COUNT(*)']?> осіб;</div>
            <?php endforeach;?>
        
        <div class="stiloznachzvit">- з них кожного виду інвалідності: *знач*;</div>
    </div>
    <div class="stilozvit">
        3. Результат проведенної роботи:
        <div class="stiloznachzvit">- працевлаштовано *знач* осіб;</div>
        <div class="stiloznachzvit">- надано допомоги у працевлаштуванні *знач* особам;</div>
        <div class="stiloznachzvit">- надання допомоги з оформлення документів *знач* особам;</div>
        <div class="stiloznachzvit">- ведеться робота з пошуку робочого місця для *знач* осіб;</div>
        <div class="stiloznachzvit">- відновлено у наданні допомоги *знач* особам;</div>
        <div class="stiloznachzvit">- надано *знач* консультацій</div>
    </div>
    <div class="stilozvit">
        4. Направлено ... (звернутися) до:
        <div class="stiloznachzvit">- місцевих органів державної влади *знач* осіб;</div>
        <div class="stiloznachzvit">- центрів зайнятості *знач* осіб;</div>
        <div class="stiloznachzvit">- громадських організацій *знач* осіб;</div>
        <div class="stiloznachzvit">- приватних роботодавців *знач* осіб;</div>
    </div>
    <div class="stilozvit">
        5. Соціальний супровід проводиться з *знач* клієнтами.
    </div>
</div>
<br><br><br><br><br>
<div class="row">
    <a href="" class="thumbnail">
        <h6>
            <i class="fa fa-file-pdf-o fa-3x" aria-hidden="true"> Сформувати PDF файл</i>
        </h6>
    </a>
</div>