<?=\Library\Session::getFlash()?>


<form class="form-signin" method="post">
    <h2 class="form-signin-heading">Авторизація</h2>
    <label for="inputEmail" class="sr-only">Email address</label>
    <input type="email" class="form-control" placeholder="Email address" value="<?=$form->email?>" name="email"><br>
    <label for="inputPassword" class="sr-only">Password</label>
    <input type="password" class="form-control" placeholder="Password" name="password">

    <button class="btn btn-lg btn-primary btn-block" type="submit">ВХІД</button>
</form>


